model_name: 'Gait Transformer'
training_data: 'gait_train.tsv' #name of the file for the training dataset.
testing_data: 'gait_test.tsv' #name of the file for the testing dataset.
base_URL: 'Data/'
###########################################################
# Hyperparameters for fitting a model.
###########################################################
num_epochs: 1
validation_split: 0.2 #default 0.2
batch_size: 8 #default 64
learning_rate: 1.0e-4 #default 1.0e-4

###########################################################
# Hyperparameters for building a model.
###########################################################
num_layers: 4 #default 4
head_size: 256 #default 256
num_heads: 4 #default 4
ff_dim: 4 #default 4
mlp_units: 128 #default 128
mlp_dropout: 0.4 #default 0.4
dropout: 0.25 #default 0.25
